### ISSUE TITLE
update readme - it is out of sync !

### ISSUE THREAD

**Issue by vincentclaes** [hpb-project/ghpb-testnet#14]
the steps to perform in the readme are out of date!
I am a Go noob so I can't do it (for now ;))

> hi, Vincentclaes , I am glad to tell you that the Readme has been updated . More specific guides are coming soon , plz keep ur attention ,thx

**Comment by mym-xjl** [comment]
hi, Vincentclaes , I am glad to tell you that the readme has been  updated . More specific guide is coming soon , plz keep ur attention ,thx
